config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :pages, only: [:new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord

  def update_metadata
    update(metadata: Wikipedia::Api.new(name).get_metadata)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.all
  end

  def new
    @page = Page.new
  end

  def create
    Page.create(page_params).update_metadata
    redirect_to root_path
  end

  private

  def page_params
    params.require(:page).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wikipedia</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Test task</h1>
<%= link_to 'Add page', new_page_path %>
<div class="row border">
  <div class="col-md-5">
    <% @pages.each do |page| %>
      <div class="row">
        <button class="wiki-content">
          <div class="col-12 wiki-name" data-meta-content="<%= page.metadata.to_json %>">
            <%= page.name %>
          </div>
        </button>
      </div>
    <% end %>
  </div>
  <div class="col-md-7 border" id="meta-content">
  </div>
</div>

app/views/pages/new.html.erb
<h2>Add page </h2>

<%= form_for @page do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit :add %>
<% end %>